[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/list-posts"
  to = "/.netlify/functions/proxy-list-posts"
  status = 200
  force = true

[[headers]]
  for = "/api/list-posts"
  [headers.values]
    Access-Control-Allow-Origin = "*"
